lib/aerospike/value/value.rb
spec/aerospike/client_spec.rb
spec/support/utils.rb

Symbol are first class citizens in Ruby. Ruby dev has the habit to use them as key for hashes. To tell the truth, when I wrote my first AS Key, I put a symbol as user_key and I was surprised AS refused it.
I'm pretty sure I'm not the only one and I think it's a reasonable deal to handle ruby symbol silently as its text counterpart in AS ruby client.

Accept ruby symbol as user_key value. Treat them as text.

---

lib/aerospike/result_code.rb

Ruby client is missing some keys, which is harmful to the understanding of the error. See #17 and #18

Add missing result_code

---

lib/aerospike.rb

I have a module that include `Aerospike`. I have another class that include the first module and try to instance `Aerospike` classes like `Client` and `Statement`. `Client` class is instanced, but when I try to instance `Statement` I get this error:
```
NameError: uninitialized constant Statement
from /opt/rb/var/www/rb-rails/lib/<route to rb>.rb:41:in `query'
from (irb):2
from /usr/local/rvm/gems/ruby-2.1.2/gems/railties-4.0.12/lib/rails/commands/console.rb:90:in `start'
from /usr/local/rvm/gems/ruby-2.1.2/gems/railties-4.0.12/lib/rails/commands/console.rb:9:in `start'
from /usr/local/rvm/gems/ruby-2.1.2/gems/railties-4.0.12/lib/rails/commands.rb:62:in `<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in `<main>'
```
To solve this error I require `Statement` class on …

Fixed an error when try to instance Statement class

---

lib/aerospike/query/filter.rb

This method can be used to log query information. It's useful to log full queries (like ActiveRecord) when you are debugging a Rails app.

Added `to_s`method to filters

---

lib/aerospike/command/read_command.rb
spec/aerospike/client_spec.rb

Ran into a syntax error when performing increment batch operations on empty records.
Included is a test that was failing on the old code path. Note that the broken code path is only triggered when performing a single add batch operation; performing an add + get batch operation does not trigger this path.

Fix record initialization issue

---

lib/aerospike/policy/client_policy.rb
spec/aerospike/policy/client_policy_spec.rb

Fix client policy to actually accept fail_if_not_connected parameter from constructor opts.

fail_if_not_connected param for ClientPolicy

---

lib/aerospike/client.rb

Hi,
Client#hash_to_bin raises ``NoMethodError: undefined method `Parse' for Aerospike::Exceptions:Module`` when the keys in the map are not strings instead of the intended `Aerospike::Exceptions::Parse`.
This fix properly initializes `Aerospike::Exceptions::Parse`.

Fix raise of Aerospike::Exceptions::Parse in Client#hash_to_bin

---

lib/aerospike/policy/policy.rb
spec/aerospike/policy/policy_spec.rb

`max_retiries` => `max_retries`

Fix a typo in the "max_retries" policy parameter name

---

lib/aerospike/cluster/cluster.rb

It was typed `Exection` instead of `Exception`

Fix typo handling exception when validating cluster's nodes

---

docs/datamodel.md

Use Ruby syntax instead of Go syntax

Fix syntax error in datamodel documentation

---

lib/aerospike/client.rb
lib/aerospike/cluster/partition.rb
lib/aerospike/command/read_command.rb

Micro-optimizations. Not a huge performance improvement but low hanging fruits for getting rid of allocations during common operations
These are avoided when running 10k put + 10k get
```
aerospike/client.rb:115   T_HASH   10000
aerospike/client.rb:294   T_HASH   10000
aerospike/client.rb:292  T_ARRAY   10000
aerospike/command/read_command.rb:130 T_STRING   10000
aerospike/cluster/partition.rb:34 T_STRING   40000
```

Avoid easy allocations

---

lib/aerospike/host/parse.rb
lib/aerospike/peers/parse.rb
lib/aerospike/socket/tcp.rb
lib/aerospike/utils/string_parser.rb
spec/aerospike/host/parse_spec.rb
spec/aerospike/peers/parse_spec.rb
spec/aerospike/socket/tcp_spec.rb

Parse and connect to IPv6 hosts correctly

Support for IPv6

---

tools/benchmark/benchmark.rb

* Use actual elapsed time to calculate TPS instead of assuming exact, 1 second intervals
* Terminate benchmark on interrupt (CTRL-C)
* Print total TPS for entire benchmark duration at end

Minor benchmark improvements

---

.travis.yml
Gemfile
lib/aerospike/socket/ssl.rb
spec/aerospike/client_spec.rb
spec/aerospike/socket/ssl_spec.rb
spec/support/utils.rb

* Add JRuby back to CI test matrix
* Remove dependency on `msgpack-jruby` gem which has been merged into `msgpack` gem
* TLS-encrypted connections not supported on JRuby for now, due to jruby/jruby-openssl#172

JRuby support

---

lib/aerospike/client.rb
lib/aerospike/policy/client_policy.rb
spec/aerospike/client_spec.rb
spec/aerospike/policy/client_policy_spec.rb

* If no policy is set explicity for a client command,
Client#create_policy falls back to use default_*_policy policies
instead of creating a new policy instance.
* Add ClientPolicy#policies property to set default policies via the
Client constructor.
* Split Client#default_policy into Client#default_read_policy and
Client#default_info_policy.
Resolves #74

Fix setting of default policies

---

.gitignore
spec/aerospike/batch_spec.rb
spec/aerospike/bin_spec.rb
spec/aerospike/cdt_list_spec.rb
spec/aerospike/cdt_map_spec.rb
spec/aerospike/client_spec.rb
spec/aerospike/geo_json_spec.rb
spec/aerospike/index_spec.rb
spec/aerospike/info_spec.rb
spec/aerospike/key_spec.rb
spec/aerospike/policy/client_policy_spec.rb
spec/aerospike/policy/policy_spec.rb
spec/aerospike/policy/write_policy_spec.rb
spec/aerospike/query_spec.rb
spec/aerospike/record_spec.rb
spec/aerospike/scan_spec.rb
spec/aerospike/security_spec.rb
spec/aerospike/udf_spec.rb
spec/aerospike/value_spec.rb

This PR:
- ignores bundler dependencies (installing gems to `vendor/bundle` is a common practice),
- removes `require 'spec_helper` statement, since`spec_helper` already included in `.rspec` file.

development tweaks

---

.travis.yml
.travis/aerospike.conf

* Switch from Ubuntu Trusty (14.04) to Ubuntu Xenial (16.04) image.
* Update Aerospike server config to remove deprecated settings.

Update Travis CI build

---

lib/aerospike/command/command.rb
lib/aerospike/result_code.rb
lib/aerospike/value/value.rb
spec/aerospike/cdt_list_spec.rb
spec/aerospike/cdt_map_spec.rb
spec/spec_helper.rb
spec/support/matchers.rb

Fix a couple of tests that were broken due to minor changes in server behaviour:
* CDT read ops now require INFO1_READ flag.
* Some CDT ops now return a new "op not applicable" result code instead of a generic parameter error.
* Behaviour for some CDT ops with return type NONE has changed.
* Fix usage of INFINITY & WILDCARD values - not sure how this ever worked in the past...

Misc fixes for various broken tests

---

lib/aerospike/client.rb

Most Ruby apps run inside threaded processes, like Sidekiq or Puma. Your code is only executed in a Worker thread spawned by the main thread. The gotcha is, if you spawn a thread with `abort_on_exception = true` and this thread raises an exception, the exception will **always** propagate to the main thread. 
This means that Sidekiq/Puma will exit due to an unexpected error. 
There are be at least a few cases when the Aerospike Client might raise errors in the batch commands:
1. Timeouts
2. Network errors
3. Cluster rebalancing / adding, or removing nodes
This PR only fixes the batch index command, but I think it'd be great to fix patch the other places where abort_on_exception is used. 
Please see the two examples below of the intricacies of abort_on_exception.
Try running this code …

Remove Thread#abort_on_exception from batch_index_command

---

lib/aerospike/cluster.rb

Remove Timeout in favor of thread.join(timeout)

---

lib/aerospike/command/admin_command.rb

fix error:
Traceback (most recent call last):
9: from /Users/dotanmor/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:22:in `<main>'
8: from /Users/dotanmor/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:22:in `eval'
7: from /Users/dotanmor/.rvm/gems/ruby-2.6.6/bin/irb:23:in `<main>'
6: from /Users/dotanmor/.rvm/gems/ruby-2.6.6/bin/irb:23:in `load'
5: from /Users/dotanmor/.rvm/gems/ruby-2.6.6/gems/irb-1.2.7/exe/irb:11:in `<top (required)>'
4: from (irb):30
3: from /Users/dotanmor/.rvm/gems/ruby-2.6.6/gems/aerospike-2.21.1/lib/aerospike/client.rb:816:in `query_user'
2: from /Users/dotanmor/.rvm/gems/ruby-2.6.6/gems/aerospike-2.21.1/lib/aerospike/command/admin_command.rb:180:in `query_user'
1: from /Users/dotanmor/.rvm/gems/ruby-2.6.6/gems/aerospike-2.21.1/lib/aerospike/command/admin_command. …

fix read_users to avoid error

---

lib/aerospike/batch_read.rb
lib/aerospike/command/batch_operate_command.rb
spec/aerospike/batch_operate_spec.rb

This pull request:
- fixes invalid local variable reference in `BatchOperateCommand`
```bash
/aerospike-client-ruby/lib/aerospike/command/batch_operate_command.rb:95:in `block in write_buffer': undefined local variable or method `br' for an instance of Aerospike::BatchOperateCommand (NameError)
attr.adjust_read(br.ops)
^^
from /aerospike-client-ruby/lib/aerospike/command/batch_operate_command.rb:81:in `each'
from /aerospike-client-ruby/lib/aerospike/command/batch_operate_command.rb:81:in `each_with_index'
from /aerospike-client-ruby/lib/aerospike/command/batch_operate_command.rb:81:in `write_buffer'
from /aerospike-client-ruby/lib/aerospike/command/command.rb:718:in `execute'
from /aerospike-client-ruby/lib/aerospike/client.rb:973:in `execute_command'
from …
```

fix: BatchRead with operations

---

lib/aerospike/exp/exp_map.rb

That fixes the following error when map expressions are used:
```bash
NameError:
uninitialized constant Aerospike::Exp::Map::MapReturnType
/aerospike-client-ruby/lib/aerospike/exp/exp_map.rb:479:in `get_value_type'
/aerospike-client-ruby/lib/aerospike/exp/exp_map.rb:294:in `get_by_key_range'
```

fix: use correct namespace for the MapReturnType
